version: "3.9"

services:
  go-app:
    container_name: go-app
    image: go-basic-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go-basic-db
  go_basic-db:
    container_name: go-basic-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: postgres
      POSTGRES_DB: code043
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
